insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Squats', 'Hopp, hopp! Arsch auf den Boden!', 3, 3, 2, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (7, 7);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Klimmzug', 'Arschbacken zusammen und hoch!', 2, 1, 2, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (8, 1);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (8, 6);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (8, 9);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Jogging', 'Laufen. Aber nicht zu schnell!', 1, 1, 4, null);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Jogging', 'Laufen. Aber bitte nicht zu schnell!', 1, 1, 4, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (9, 7);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Arm Curl', 'BIZEPS!!!!', 1, 1, 2, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (10, 1);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Squats', 'Arsch auf den Boden!', 3, 3, 2, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (5, 7);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Klimmzug', 'Zieh dich hoch, Junge!', 2, 1, 2, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (5, 1);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (5, 6);
insert into UEBUNG (bezeichnung_uebung, beschreibung_uebung, schwierigkeitsgrad, verletzungsrisiko, uebungskategorie, bild_uebungsablauf) values ('Klimmzug', 'Zieh dich hoch!', 2, 1, 3, src\main\webapp\resources\images\tempImage.jpg);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (5, 1);
insert into MUSKELGRUPPE_UEBUNG (uebung, muskelgruppe) values (5, 6);
